function montage = dprst_montage_rearrange_channels(D)
%DPRST_MONTAGE_REARRANGE_CHANNELS Creates the montage struct for 
%rearranging channel labels for 2 subjects of the DPRST study with wrong 
%cabling during measurement.
%   IN:     options     - the struct that holds all analysis options
%   OUT:    montage     - the montage struct with labels and montage matrix

montage = struct;

% channel labels
montage.labelorg = chanlabels(D);
    %{
    {...
    'Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', ...
    'F7', 'F8', 'T7', 'T8', 'P7', 'P8', 'Fz', 'Cz', 'Pz', 'EOG', 'FC1', ...
    'FC2', 'CP1', 'CP2', 'FC5', 'FC6', 'CP5', 'CP6', 'FT9', 'FT10', ...
    'TP9', 'TP10', 'F1', 'F2', 'C1', 'C2', 'P1', 'P2', 'AF3', ...
    'AF4', 'FC3', 'FC4', 'CP3', 'CP4', 'PO3', 'PO4', 'F5', 'F6', ...
    'C5', 'C6', 'P5', 'P6', 'AF7', 'AF8', 'FT7' ,'FT8', 'TP7', ...
    'TP8', 'PO7', 'PO8', 'FCz', 'CPz', 'POz', 'Oz', 'pulse'};
    %}
montage.labelnew = {montage.labelorg{33:64}, ...
                    montage.labelorg{1:32}, ...
                    montage.labelorg{65:end}};

tra = eye(numel(montage.labelorg));
montage.tra = tra;

end
